{% set version = "0.25.0" %}

package:
  name: bacon-ls
  version: {{ version }}

source:
  url: https://github.com/crisidev/bacon-ls/archive/{{ version }}.tar.gz
  sha256: 778daa6102df7223fa654816dc908cbe1593789645bc9af13d04ddc742a7ead6

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
    - perl
    - pkg-config
  host:
    - openssl

test:
  commands:
    - bacon-ls &  # [not win]
    - exe_pid=$!  # [not win]
    - trap "kill -SIGTERM ${exe_pid}" SIGTERM  # [not win]
    - start /b bacon-ls   # [win]
    - if %errorlevel% neq 0 exit %errorlevel%  # [win]
    - taskkill /F /im bacon-ls.exe  # [win]
    - if %errorlevel% neq 0 exit %errorlevel%  # [win]

about:
  home: https://github.com/crisidev/bacon-ls
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: A Language Server for Rust using Bacon diagnostics
  dev_url: https://github.com/crisidev/bacon-ls

extra:
  recipe-maintainers:
    - danielnachun
